cabal-version:      3.0
name:               aoc-haskell
version:            0.1.0.0
-- synopsis:
-- description:
license:            MIT
license-file:       LICENSE
author:             Dmitry Kvasnikov
maintainer:         dmitry.kvasnikov@gmail.com
-- copyright:
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  Types
                    , Solutions
                    , Years.Y2015.Day1
                    , Years.Y2015.Day2
    -- other-modules:
    -- other-extensions:
    build-depends:
        base ^>=4.20.2.0
      , split 
    hs-source-dirs:   src
    default-language: GHC2024

executable aoc-haskell
    import:           warnings
    main-is:          Main.hs
    -- other-modules:
    -- other-extensions:
    build-depends:
        base ^>=4.20.2.0
      , directory  
      , aoc-haskell

    hs-source-dirs:   app
    default-language: GHC2024
